version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: simple_lms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:7
    container_name: mongo_db
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  web:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - mongodb
      - rabbitmq
    environment:
      DB_NAME: simple_lms
      DB_USER: postgres
      DB_PASSWORD: password123
      DB_HOST: db
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/1
      MONGO_URI: mongodb://mongodb:27017/
      MONGO_DB_NAME: lms_logs
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//

  celery-worker:
    build: .
    container_name: celery_worker
    command: celery -A config worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - mongodb
      - rabbitmq
    environment:
      DB_NAME: simple_lms
      DB_USER: postgres
      DB_PASSWORD: password123
      DB_HOST: db
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/1
      MONGO_URI: mongodb://mongodb:27017/
      MONGO_DB_NAME: lms_logs
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//

  celery-beat:
    build: .
    container_name: celery_beat
    command: celery -A config beat -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - mongodb
      - rabbitmq
    environment:
      DB_NAME: simple_lms
      DB_USER: postgres
      DB_PASSWORD: password123
      DB_HOST: db
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/1
      MONGO_URI: mongodb://mongodb:27017/
      MONGO_DB_NAME: lms_logs
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//

  flower:
    build: .
    container_name: celery_flower
    command: celery -A config flower --port=5555
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    depends_on:
      - db
      - redis
      - mongodb
      - rabbitmq
    environment:
      DB_NAME: simple_lms
      DB_USER: postgres
      DB_PASSWORD: password123
      DB_HOST: db
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/1
      MONGO_URI: mongodb://mongodb:27017/
      MONGO_DB_NAME: lms_logs
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//

volumes:
  postgres_data:
  mongodb_data:
  rabbitmq_data: